# Generated by Django 3.2.3 on 2021-05-17 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CharterCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Marina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=64)),
                ('country', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Yacht',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('year', models.IntegerField(max_length=4)),
                ('length', models.IntegerField(max_length=8)),
                ('max_person', models.IntegerField(max_length=8)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('charter_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingyacht.chartercompany')),
            ],
        ),
        migrations.CreateModel(
            name='YachtCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(choices=[(1, 'monohulls'), (2, 'catamarans'), (3, 'Motor Boat'), (4, 'Trimaran')])),
            ],
        ),
        migrations.CreateModel(
            name='YachtReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('yacht', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bookingyacht.yacht')),
            ],
        ),
        migrations.AddField(
            model_name='yacht',
            name='yacht_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingyacht.yachtcategory'),
        ),
        migrations.AddField(
            model_name='chartercompany',
            name='marina',
            field=models.ManyToManyField(to='bookingyacht.Marina'),
        ),
    ]
