# Generated by Django 3.2.3 on 2021-05-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingyacht', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yacht',
            name='length',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='yacht',
            name='max_person',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='yacht',
            name='year',
            field=models.IntegerField(),
        ),
    ]
