# Generated by Django 3.2.3 on 2021-05-24 10:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookingyacht', '0003_alter_yachtcategory_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yachtcategory',
            name='category',
            field=models.IntegerField(choices=[(1, 'monohulls'), (2, 'catamarans'), (3, 'Motor Boat'), (4, 'Trimaran')]),
        ),
        migrations.AlterUniqueTogether(
            name='yachtreservation',
            unique_together={('user', 'date')},
        ),
    ]
