# Generated by Django 3.2.3 on 2021-05-24 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingyacht', '0004_auto_20210524_1031'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='yachtreservation',
            unique_together=set(),
        ),
    ]
